#!/bin/bash
#PBS -N XylellaPreproc
#PBS -q large
#PBS -l nodes=1:ppn=16
#PBS -l mem=45gb
#PBS -l walltime=05:00:00
#PBS -j oe
#PBS -o logs_preproc.log

cd $PBS_O_WORKDIR

source /home/aubjyd001/miniforge3/etc/profile.d/conda.sh

conda activate biol-7180

bash preprocess_homalodisca.sh \
  -a R1.fastq.gz \
  -b R2.fastq.gz \
  -g genomes/homalodisca/homalodisca_genome.fasta \
  -s Apollo_12 \
  -t 16
